"""Add HistorialMovimientos table

Revision ID: 254a99a8b001
Revises: f0fa4080236f
Create Date: 2024-11-15 12:19:06.670615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254a99a8b001'
down_revision = 'f0fa4080236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_movimientos')
    # ### end Alembic commands ###
