"""added types2

Revision ID: 50fe8cd8d030
Revises: 990e2cab8dd2
Create Date: 2024-11-25 19:38:53.138723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fe8cd8d030'
down_revision = '990e2cab8dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cuenta', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('tipo_cuenta')

    # ### end Alembic commands ###
