"""Make numero_zona unique and reference it from Clientes

Revision ID: c13df7bcc120
Revises: 
Create Date: 2024-10-16 00:20:40.234996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13df7bcc120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antenas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('antena_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antena_id'], ['antenas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('numero_zona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_zona')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado_cobro', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('folio_cobro', sa.String(length=50), nullable=False),
    sa.Column('estado_factura', sa.Boolean(), nullable=False),
    sa.Column('fecha_cobro', sa.Date(), nullable=False),
    sa.Column('fecha_alerta', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.numero_zona'], ),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('folios',
    sa.Column('folio', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folios')
    op.drop_table('clientes')
    op.drop_table('zonas')
    op.drop_table('municipios')
    op.drop_table('usuarios')
    op.drop_table('antenas')
    # ### end Alembic commands ###
