"""added table

Revision ID: f0fa4080236f
Revises: 
Create Date: 2024-11-14 13:25:38.059236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fa4080236f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antenas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombreDispositivo', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ssid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('pendiente', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('antena_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antena_id'], ['antenas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunidad',
    sa.Column('id_comunidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_comunidad', sa.String(length=100), nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id_comunidad')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=13), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('num_cuenta', sa.String(length=50), nullable=True),
    sa.Column('comunidad_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=50), nullable=False),
    sa.Column('colonia', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('codigo_postal', sa.String(length=13), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado_cobro', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('fecha_cobro', sa.Date(), nullable=False),
    sa.Column('fecha_alerta', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('plan_pago', sa.String(length=50), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=True),
    sa.Column('monto_debido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidad.id_comunidad'], ),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=False),
    sa.Column('materiales', sa.String(length=255), nullable=True),
    sa.Column('tecnico', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('clientes')
    op.drop_table('comunidad')
    op.drop_table('municipios')
    op.drop_table('usuarios')
    op.drop_table('folios')
    op.drop_table('facturas')
    op.drop_table('antenas')
    # ### end Alembic commands ###
